added option -d to bin header

diff --git a/my/bin/header b/my/bin/header
--- a/my/bin/header
+++ b/my/bin/header
@@ -1,8 +1,20 @@
 #!/bin/bash
 
+delim=";"
+
+if [ "$#" -gt 2 ]; then
+    if [ "$1" != "-d" ]; then
+	echo "Error: bad arguments"
+	exit 1
+    fi
+    delim="$2"
+    shift
+    shift
+fi
+
 if [ "$#" == "2" ] && [ "$1" == "-l" ]; then
     i=0
-    head -n 1 "$2" | tr ';' '\n' | while read field; do
+    head -n 1 "$2" | tr "$delim" '\n' | while read field; do
 	i=$((i+1))
 	printf "%d\t%s\n" "$i" "$field"
     done
