updated gor to fallback to git repo root directory if any

diff --git a/my/aliases/rails b/my/aliases/rails
--- a/my/aliases/rails
+++ b/my/aliases/rails
@@ -21,13 +21,20 @@ function gotogem()
 
 function gor()
 {
+    # 1) Rails app
+    # 2) Git repository
     path=`find_rails_app_root.rb`
     if [ "$?" == "0" ]; then
 	cd $path
 	return 0
     else
-	echo "Error: no rails app found" > /dev/stderr
-	return 1
+	git rev-parse --git-dir > /dev/null 2> /dev/null
+	if [ "$?" == "0" ]; then
+	    cd "$(git rev-parse --git-dir)/.."
+	else
+	    echo "Error: no rails app nor git repository found" > /dev/stderr
+	    return 1
+	fi
     fi
 }
 
