added rails alias: reset_db

diff --git a/my/aliases/rails b/my/aliases/rails
--- a/my/aliases/rails
+++ b/my/aliases/rails
@@ -3,8 +3,7 @@
 alias ner='ne ./config/routes.rb'
 alias rs='rails s'
 alias rc='rails c'
-# alias rd="rdesc"
-# alias rr="rrout"
+alias rr="rrout"
 alias migrate="rake db:migrate"
 alias goc="gor && cd app/controllers"
 alias gom="gor && cd app/models"
@@ -31,6 +30,27 @@ function gogems()
 	return 0
     else
 	echo "Error: folder found" > /dev/stderr
+	return 1
+    fi
+}
+
+function rrout()
+{
+    rake routes | grep "$1"
+}
+
+function reset_db()
+{
+    path=`find_rails_app_root.rb`
+    if [ "$?" == "0" ]; then
+	rm -f "$path/db/development.sqlite3"
+	rm -f "$path/db/test.sqlite3"
+	rake db:create
+	rake db:migrate
+	rake db:seed
+	return 0
+    else
+	echo "Error: no rails app found" > /dev/stderr
 	return 1
     fi
 }
